apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: redhat-acs-secured-cluster-configured
  namespace: policies
  annotations:
    policy.open-cluster-management.io/standards: Infrastructure security
    policy.open-cluster-management.io/categories: Data security
    policy.open-cluster-management.io/controls: PR.DS-1 Data-at-rest
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: managed-cluster-security-endpoints
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: platform.stackrox.io/v1alpha1
                kind: SecuredCluster
                metadata:
                  namespace: rhacs-operator
                  name: rhacs-secured-cluster-services
                spec:
                  clusterName: '{{ fromSecret "open-cluster-management-agent" "hub-kubeconfig-secret" "cluster-name" | base64dec }}'
                  auditLogs:
                    collection: Auto
                    centralEndpoint: https://central-rhacs-operator.apps.49.integrate.zone:443
                  admissionControl:
                    listenOnCreates: false
                    listenOnEvents: true
                    listenOnUpdates: false
                  perNode:
                    collector:
                      collection: KernelModule
                      imageFlavor: Regular
                    taintToleration: TolerateTaints
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: copy-admission-control-tls
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: admission-control-tls
                  namespace: rhacs-operator
                data:
                  admission-control-cert.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "admission-control-tls").data "admission-control-cert.pem" ) hub}}'
                  admission-control-key.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "admission-control-tls").data "admission-control-key.pem" ) hub}}'
                  ca.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "admission-control-tls").data "ca.pem" ) hub}}'
                type: Opaque
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: copy-collector-tls
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: collector-tls
                  namespace: rhacs-operator
                data:
                  collector-cert.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "collector-tls").data "collector-cert.pem" ) hub}}'
                  collector-key.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "collector-tls").data "collector-key.pem" ) hub}}'
                  ca.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "collector-tls").data "ca.pem" ) hub}}'
                type: Opaque
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: copy-sensor-tls
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                kind: Secret
                apiVersion: v1
                metadata:
                  name: sensor-tls
                  namespace: rhacs-operator
                data:
                  sensor-cert.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "sensor-tls").data "sensor-cert.pem" ) hub}}'
                  sensor-key.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "sensor-tls").data "sensor-key.pem" ) hub}}'
                  ca.pem: '{{hub ( index ( lookup "v1"  "Secret" "rhacs-operator" "sensor-tls").data "ca.pem" ) hub}}'
                type: Opaque
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: rhacs-secured-clusters-binding
  namespace: policies
placementRef:
  name: acs-remote-clusters
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: redhat-acs-secured-cluster-configured
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: acs-remote-clusters
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
