apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-infrastructure-requirements
  annotations:
    policy.open-cluster-management.io/standards: NIST 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline 
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: infrastructure-requirements
        spec:
          remediationAction: enforce
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: argoproj.io/v1alpha1
                kind: Application
                metadata:
                  name: infrastructure-requirements
                  namespace: openshift-gitops
                spec:
                  destination:
                    server: 'https://kubernetes.default.svc'
                  project: default
                  source:
                    path: 'multicluster/{{ fromClusterClaim "name" }}'
                    repoURL: 'https://github.com/itsbanjo/argocd-demo.git'
                    targetRevision: HEAD
                  syncPolicy:
                    automated: {}
                    syncOptions:
                      - CreateNamespace=false
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-infrastructure-requirements
placementRef:
  name: placement-policy-infrastructure-requirements
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-infrastructure-requirements
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-infrastructure-requirements
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - {key: environment, operator: In, values: ["dev"]}
